version: '3'
services:
  balancer:
    image: nginx
    volumes:
     - ./nginx/:/etc/nginx/
    ports:
     - "8081:80"
  webapp1:
    image: "nicopaez/password-api"
  webapp2:
    image: "nicopaez/password-api"

