apiVersion: v1
kind: Pod
metadata:
  name: ejer8s
  labels:
    app: ejer8s
spec:
   containers:
    - name: ejer8s
      image: nicopaez/telegrambot:0.0.7
      envFrom:
      - secretRef:
          name: tokentelegram 
